name: Run tests and upload coverage

on:
  push

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: '6.0'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov mongomock

      - name: Run Pytest with Timeout
        run: |
          timeout 60s python -m pytest --cov --cov-report=xml tests/ || true

      - name: List Processes
        run: |
          ps aux

      - name: Cleanup Background Processes
        run: |
          pkill -f "python" || true
          pkill -f "pytest" || true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
