name: pytest

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Specify the environment (Ubuntu in this case)
    strategy:
      matrix:
        mongodb-version: ['7.0']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the code from the repository

      - name: Set up Python
        uses: actions/setup-python@v2  # Set up the desired Python version
        with:
          python-version: '3.12'  # Specify the Python version (e.g., 3.8 or latest 3.x)

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-timeout psutil

      - name: Cleanup MongoDB container
        run: |
          if [ "$(docker ps -aq -f name=mongodb)" ]; then
            docker rm -f mongodb || true
          fi
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Run Pytest with Timeout
        run: |
          timeout 10s python -m pytest tests/ || true

      - name: List Processes
        run: |
          ps aux

      - name: Cleanup Background Processes
        run: |
          pkill -f "python" || true
          pkill -f "pytest" || true